[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
rustflags = [
    "-Cforce-frame-pointers=yes",
    "-Clink-args=-no-pie",
    "-Clink-args=--script=linker.ld",
]
